# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'tempservice'
    subscriptionId: 'b117288c-e34b-4128-9016-dc8b1e3ce046'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'az301pipeline-rg'
    location: 'East US 2'
    templateLocation: 'Linked artifact'
    csmFile: 'CreateWebApp/azuredeploy.json'
    overrideParameters: '-projectName kkdeployArm -linkedTemplateUri https://raw.githubusercontent.com/kalyan369k/AzureRmPipeline-repo/main/CreateWebApp/linkedStorageAccount.json?token=ARYPW4BRCKKYWXK4ITFQWH27YKGOU'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'